image: mbeddr/mbeddr.build.docker.env

variables:
  GRADLE_USER_HOME: "gradle/.gradle"
  GRADLE_OPTS: "
      --no-daemon
      -g $GRADLE_USER_HOME 
      -PforceCI=true
      -PmpsExtensionsVersion=$MPS_EXTENSIONS_VERSION
      -PmbeddrPlatformVersion=$MBEDDR_PLATFORM_VERSION
      -PdependencyRepositories=$MBEDDR_DEPENDENCY_REPOSITORY
      -PsnapshotRepository=$MBEDDR_SNAPTHOT_REPOSITORY
      -PreleaseRepository=$MBEDDR_RELEASE_REPOSITORY
      -PnexusUsername=$NEXUS_USER 
      -PnexusPassword=$NEXUS_PASSWORD
    "

before_script:
  - java -version
  - mkdir -p $GRADLE_USER_HOME
  - chmod a+x gradlew 
  - ./gradlew --version

build:
  stage: build
  script: 
    - ./gradlew publishMbeddrPublicationToMavenRepository
  cache:
    paths:
      - $GRADLE_USER_HOME
  only:
    - web